apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateforge.fullname" . }}-frontend
  labels:
    app: gateforge-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: gateforge-frontend
    app.openshift.io/runtime: nginx
    {{- include "gateforge.labels" . | nindent 4 }}
  annotations:
    app.openshift.io/runtime: nginx
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ include "gateforge.fullname" . }}-backend"}]'
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: gateforge-frontend
  template:
    metadata:
      labels:
        app: gateforge-frontend
        app.openshift.io/runtime: nginx
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
