apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateforge.fullname" . }}-config
  labels:
    {{- include "gateforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_API_KEY: {{ .Values.ai.apiKey | default "dummy" | quote }}
  THREESCALE_ACCESS_TOKEN: {{ .Values.threescale.adminApi.accessToken | default "none" | quote }}
