apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateforge.fullname" . }}-config
  labels:
    {{- include "gateforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  THREESCALE_ACCESS_TOKEN: {{ .Values.threescale.adminApi.accessToken | default "none" | quote }}
  DATASOURCE_USERNAME: {{ .Values.postgresql.username | default "gateforge" | quote }}
  DATASOURCE_PASSWORD: {{ .Values.postgresql.password | default "gateforge" | quote }}
